unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind v split-window -h -c "#{pane_current_path}"  # Split right
bind s split-window -v -c "#{pane_current_path}"  # Split down
bind x kill-pane                                  # Close pane
bind z resize-pane -Z                             # Toggle fullscreen/frames (zoom)

# Resize
bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5

# Swap panes
bind -r H swap-pane -t "{left-of}"
bind -r J swap-pane -t "{down-of}"
bind -r K swap-pane -t "{up-of}"
bind -r L swap-pane -t "{right-of}"

bind 1 select-window -t :=1
bind 2 select-window -t :=2
bind 3 select-window -t :=3
bind 4 select-window -t :=4
bind 5 select-window -t :=5
bind 6 select-window -t :=6
bind 7 select-window -t :=7
bind 8 select-window -t :=8
bind 9 select-window -t :=9

set -g mouse on                                   # Enable mouse mode
set -g history-limit 10000                        # Scroll buffer size

set-window-option -g mode-keys vi

set -g status-bg black
set -g status-fg white
set -g status-style bg=default

# Setup 'v' to begin selection as in Vim
bind-key -T copy-mode-vi v send-keys -X begin-selection

# Press F12 to toggle local keybindings off
bind -T root F12  \
  set prefix None \;\
  set key-table off \;\
  set status-style "fg=brightblack,bg=black" \;\
  if -F '#{pane_in_mode}' 'send-keys -X cancel' \;\
  refresh-client -S

# Press F12 again to turn local keybindings back on
bind -T off F12 \
  set -u prefix \;\
  set -u key-table \;\
  set -u status-style \;\
  refresh-client -S

# Prevent exiting copy mode when dragging with mouse
unbind -T copy-mode-vi MouseDragEnd1Pane

# Hit Prefix + I to fetch these plugins after reloading tmux
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'alexwforsythe/tmux-which-key'
set -g @plugin 'tmux-plugins/tmux-yank'

run '~/.tmux/plugins/tpm/tpm'
